# Generated by Django 3.1.4 on 2021-02-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0013_auto_20201209_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='profession',
            field=models.CharField(choices=[('H', 'Zdravotníctvo'), ('E', 'Školstvo'), ('C', 'Stavbeníctvo'), ('R', 'Reštauračné služby'), ('B', 'Podnikanie'), ('O', 'Iné')], default='O', max_length=30),
        ),
    ]
