# Generated by Django 3.1.4 on 2021-03-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0014_auto_20210219_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='student',
            field=models.CharField(choices=[('1', 'Áno'), ('0', 'Nie')], default=None, max_length=3),
        ),
    ]
