# Generated by Django 3.1.4 on 2021-03-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0015_auto_20210305_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagerating',
            name='credibility',
            field=models.IntegerField(choices=[(3, 'Úplne dôveryhodný'), (2, 'Dôveryhodný'), (1, 'Skôr dôveryhodný'), (0, 'Neviem posúdiť'), (-1, 'Skôr nedôveryhodný'), (-2, 'Nedôveryhodný'), (-3, 'Úplne nedôveryhodný')], default=None),
        ),
    ]
