# Generated by Django 3.1.4 on 2021-03-12 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0016_auto_20210305_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TextField(max_length=50)),
                ('log', models.CharField(choices=[('CS', 'Začiatok dotazníka dôveryhodnosti'), ('CE', 'Odoslanie dotazníka dôveryhodnosti'), ('MS', 'Začiatok dotazníka mediálnej gramotnosti')], default=None, max_length=30)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_generator.participant')),
            ],
        ),
    ]
