# Generated by Django 3.1.4 on 2021-03-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0018_logs_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='participant',
            field=models.IntegerField(),
        ),
    ]
