# Generated by Django 3.1.4 on 2021-03-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0019_auto_20210312_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='log',
            field=models.CharField(choices=[('PS', 'Zobrazenie hodnotenej stránky'), ('CE', 'Odoslanie dotazníka dôveryhodnosti'), ('MS', 'Začiatok dotazníka mediálnej gramotnosti')], default=None, max_length=30),
        ),
    ]
