# Generated by Django 3.1.4 on 2021-03-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0020_auto_20210312_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.CharField(choices=[('T', '15-19'), ('Y', '20-24'), ('A1', '25-34'), ('A2', '35-44'), ('A3', '45-54'), ('A4', '55-64'), ('S', '65+')], default=None, max_length=10),
        ),
    ]
