# Generated by Django 3.1.4 on 2021-03-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0021_auto_20210313_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagerating',
            name='scroll_log',
            field=models.TextField(default=None, null=True),
        ),
    ]
