# Generated by Django 3.1.4 on 2021-03-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0022_pagerating_scroll_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagerating',
            name='time_end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagerating',
            name='time_start',
            field=models.IntegerField(default=0),
        ),
    ]
