# Generated by Django 3.1.4 on 2021-03-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0024_auto_20210316_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagerating',
            name='scroll_log',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pagerating',
            name='time_end',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pagerating',
            name='time_start',
            field=models.BigIntegerField(default=0),
        ),
    ]
